# This file configures the hello-world app which serves public web traffic.
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres-gke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres-app
          # Replace $GCLOUD_PROJECT with your project ID
          image: gcr.io/my-project-123-259602/postgres-gke:v1
          # This app listens on port 8080 for web traffic by default.
          ports:
            - containerPort: 5432
          env:
            - name: PORT
              value: "5432"
