@startuml
!include stylesheet.puml
(*) --> "User presses check out"
    -->===PAR1_START===

    ===PAR1_START=== --> "**Checkout:**\nbegin check out process (start the timer)"
      -->===PAR1_END===

    ===PAR1_START=== --> "**Cart/Inventory:**\nsubtract items in cart from inventory"
      -->===PAR1_END===

    ===PAR1_END===--> "Authorize payment"

if "Successful?" then
  -->[Yes] "**Order/Cart:**\ncreate order from cart"
  --> "**Cart:**\nempty cart"
  --> "**Checkout:**\nend check out process (stop timer)"
  --> (*)
else
  ->[No] ===PAR2_START===

  ===PAR2_START=== --> "Show error message to user"
    --> ===PAR2_END===

  ===PAR2_START=== --> "**Checkout:**\nEnd check out process (stop timer)"
    --> ===PAR2_END===

  ===PAR2_END===--> (*)
@enduml
