# For more details: https://docs.travis-ci.com
language: node_js # the base for this build

node_js:
  - 8 # the version of the base

dist: trusty # the platform for the build: Ubuntu trusty

# Integrating Docker: https://docs.travis-ci.com/user/docker/
# Eventually we also want to write tests and run `npm test`

script: # scripts to run on the service package
  - npm run lint

# node_modules is cached by default by Travis