version: "3"
services:
  db:
    extends:
      file: ./db/docker-compose.yml
      service: postgres
  node-server:
    container_name: microservices-server
    restart: always
    image: node:7
    depends_on: db
    expose:
      - 3000
    ports:
      - 3000:3000
    command: npm start
    links:
      - db
  gateway:
    container_name: api-gateway
    restart: always
    image: graphql/gateway
    depends_on:
      - node-server
    expose:
      - 5000
    ports:
      - 5000:5000
    command: nodemon src/index.js
    links:
      - node-server
