# TODO: the actual usernames/passwords shouldn't be stored in this file. We need
# a way to put those somewhere that's not in version control.
#
# Use docker-compose file version 3
version: "3"
services:
  # Database service
  postgres:
    # Image based on Alpine is smaller
    image: "postgres:12-alpine"
    container_name: "postgres"
    environment:
      # The password for the database, can be changed to whatever.
      # Default username is 'postgres', can be changed with POSTGRES_USER.
      # Another useful variable is POSTGRES_DB, the name of the database.
      # Ref: https://hub.docker.com/_/postgres
      POSTGRES_PASSWORD: northeastern

    # Forward ports, format 'container:host'
    ports:
      - 5432:5432

    # Mount local directories on the container filesystem
    volumes:
      # A place to store postgres data
      - ./db/db-data:/var/lib/postgresql/data
      # Script to initialize a test database
      - ./db/test-db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    restart: unless-stopped

  # Pgadmin service (web interface)
  pgadmin:
    image: "dpage/pgadmin4"

    # Can't have the web interface without a database
    depends_on:
      - postgres
    container_name: "pgadmin"
    environment:
      # Credentials used to sign in to the web interface
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - ./db/pgadmin:/var/lib/pgadmin
    ports:
      # Use the value of an environment variable if it's set. If not, use local
      # port 5050 for the web interface (port 80 in the container).
      - "${PGADMIN_PORT:-5050}:80"
    restart: unless-stopped
  inventory-management:
    build: ./inventory-management
    container_name: "inventory-management"
    # Forward ports, format 'container:host'
    ports:
      - 3020:3020
    # Mount local directories on the container filesystem.
    # Should not happen in production.
    volumes:
      - ./inventory-management/src:/usr/app/src
      - ./inventory-management/app.js:/usr/app/app.js
      - ./inventory-management/process.json:/usr/app/process.json
      - ./inventory-management/registrations.js:/usr/app/registrations.js
      - ./inventory-management/.inventory-managementrc:/usr/app/.inventory-managementrc
      - ./inventory-management/log:/usr/app/log
      - ./inventory-management/tests:/usr/app/tests
    restart: unless-stopped

  cart:
    build: ./cart
    container_name: "cart"

    # Forward ports, format 'container:host'
    ports:
      - 3000:3000

    # Mount local directories on the container filesystem.
    # Should not happen in production.
    volumes:
      - ./cart/src:/usr/app/src
      - ./cart/app.js:/usr/app/app.js
      - ./cart/process.json:/usr/app/process.json
      - ./cart/registrations.js:/usr/app/registrations.js
      - ./cart/.cartrc:/usr/app/.cartrc
      - ./cart/log:/usr/app/log
      - ./cart/test:/usr/app/test
      # The above line takes care of making the log dir accessible, but should be
      #   handled differently in production.

    restart: unless-stopped
  api-gateway:
    build: ./graphql-api-gateway-poc
    container_name: "api-gateway"
    volumes:
      - ./graphql-api-gateway-poc/src:/usr/app/src
      - ./graphql-api-gateway-poc/process.json:/usr/app/process.json
      - ./graphql-api-gateway-poc/log:/usr/app/log
    links:
      - members-graphql-service
    expose:
      - 3050
    ports:
      - 3050:3050
    environment:
      GRAPHQL_SERVICE: members-graphql-service
  members-graphql-service:
    build: ./members-graphql-service
    container_name: "members-graphql-service"
    volumes:
      - ./members-graphql-service/index.js:/usr/app/index.js
      - ./members-graphql-service/datasource.js:/usr/app/datasource.js
      - ./members-graphql-service/process.json:/usr/app/process.json
      - ./members-graphql-service/src:/usr/app/src
      - ./members-graphql-service/log:/usr/app/log
    expose:
      - 5000
    ports:
      - 5000:5000
    environment:
      BOILERPLATE_SERVICE: boilerplate
