# TODO: the actual usernames/passwords shouldn't be stored in this file. We need
# a way to put those somewhere that's not in version control.
#
# Environment variables come from .env
# https://docs.docker.com/compose/compose-file/#variable-substitution
#
# Use docker-compose file version 3
version: "3"
services:
  # Database service
  postgres:
    # Image based on Alpine is smaller
    image: "postgres:12-alpine"
    container_name: "${POSTGRES_HOST}"
    env_file:
      - .env

    # Forward ports, format 'container:host'
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}

    # Mount local directories on the container filesystem
    volumes:
      # A place to store postgres data
      - ./db/db-data:/var/lib/postgresql/data
      # Script to initialize a test database
      - ./db/test-db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    restart: unless-stopped

  # Pgadmin service (web interface)
  pgadmin:
    image: "dpage/pgadmin4"

    # Can't have the web interface without a database
    depends_on:
      - postgres
    container_name: "${PGADMIN_HOST}"
    env_file:
      - .env
    volumes:
      - ./db/pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT}:80"
    restart: unless-stopped

  inventory-management:
    build: ./inventory-management
    container_name: "${INVENTORY_HOST}"
    # Forward ports, format 'container:host'
    ports:
      - ${INVENTORY_PORT}:${INVENTORY_PORT}
    # Mount local directories on the container filesystem.
    # Should not happen in production.
    volumes:
      - ./inventory-management/src:/usr/app/src
      - ./inventory-management/app.js:/usr/app/app.js
      - ./inventory-management/process.json:/usr/app/process.json
      - ./inventory-management/registrations.js:/usr/app/registrations.js
      - ./inventory-management/.inventory-managementrc:/usr/app/.inventory-managementrc
      - ./inventory-management/log:/usr/app/log
      - ./inventory-management/tests:/usr/app/tests
    restart: unless-stopped

  cart:
    build: ./cart
    container_name: "${CART_HOST}"

    # Forward ports, format 'container:host'
    ports:
      - ${CART_PORT}:${CART_PORT}

    env_file:
      - .env

    # Mount local directories on the container filesystem.
    # Should not happen in production.
    volumes:
      - ./cart/src:/usr/app/src
      - ./cart/app.js:/usr/app/app.js
      - ./cart/process.json:/usr/app/process.json
      - ./cart/registrations.js:/usr/app/registrations.js
      - ./cart/.cartrc:/usr/app/.cartrc
      - ./cart/log:/usr/app/log
      - ./cart/test:/usr/app/test
      # The above line takes care of making the log dir accessible, but should be
      #   handled differently in production.

    restart: unless-stopped

  api-gateway:
    build: ./graphql-api-gateway-poc
    container_name: "${API_GW_HOST}"
    volumes:
      - ./graphql-api-gateway-poc/src:/usr/app/src
      - ./graphql-api-gateway-poc/process.json:/usr/app/process.json
      - ./graphql-api-gateway-poc/log:/usr/app/log
    links:
      - members-graphql-service
    expose:
      - ${API_GW_PORT}
    ports:
      - ${API_GW_PORT}:${API_GW_PORT}
    env_file:
      - .env

  members-graphql-service:
    build: ./members-graphql-service
    container_name: "${MEMBERS_GQL_HOST}"
    volumes:
      - ./members-graphql-service/index.js:/usr/app/index.js
      - ./members-graphql-service/datasource.js:/usr/app/datasource.js
      - ./members-graphql-service/process.json:/usr/app/process.json
      - ./members-graphql-service/src:/usr/app/src
      - ./members-graphql-service/log:/usr/app/log
    expose:
      - ${MEMBERS_GQL_PORT}
    ports:
      - ${MEMBERS_GQL_PORT}:${MEMBERS_GQL_PORT}
    env_file:
      - .env

  checkout:
    build: ./checkout
    container_name: "${CHECKOUT_HOST}"

    # Forward ports, format 'container:host'
    ports:
      - ${CHECKOUT_PORT}:${CHECKOUT_PORT}

    env_file:
      - .env

    # Mount local directories on the container filesystem.
    # Should not happen in production.
    volumes:
      - ./checkout/src:/usr/app/src
      - ./checkout/app.js:/usr/app/app.js
      - ./checkout/process.json:/usr/app/process.json
      - ./checkout/registrations.js:/usr/app/registrations.js
      - ./checkout/.checkoutrc:/usr/app/.checkoutrc
      - ./checkout/log:/usr/app/log
      - ./checkout/test:/usr/app/test
      # The above line takes care of making the log dir accessible, but should be
      #   handled differently in production.

    restart: unless-stopped
